### PR TITLE
feat: Add assets on account balance get

### PR DESCRIPTION
**Pull request by anhbaysgalan1**
# Title

__Please add a description to this PR.__

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring / Technical debt

## What parts of the code are impacted ?
__Please describe the impacted parts of the code.__

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by anhbaysgalan1** [comment]
@gfyrag

**Comment by gfyrag** [comment]
@anhbaysgalan1 Can you explain the purpose of this PR?

**Comment by gfyrag** [comment]
@anhbaysgalan1 Hi! The only way this work is if you POST the assets data on the wallet. But it does not reflect the reality. Or I miss something maybe.

**Comment by anhbaysgalan1** [comment]
@gfyrag  if there is no balance it will return only balance name, but independent users need to check their balance at the current time concurrently. This request is needed i think6

**Comment by gfyrag** [comment]
@anhbaysgalan1 I'm sorry, i really don't understand.
Even with these changes, you can credit/debit balances as much as you want, the "assets" property of the balance will still be empty. The only way to get assets of a balance is to make a GET /wallets/<walletId>/balances/<balanceName> request, which in turn make a GET /<ledger>/accounts/<balanceAccount> which return volumes.
The only thing these changes seems to allow is to be able to PUT "assets" property by the client. But it can not reflect underlying properly. Is that the wanted behaviour?

**Pull request closed without merging**
